version: '3'
services:
  app:
    build:    
      context: .
      dockerfile: Dockerfile
    image: nodejs_12_13
    container_name: nodejs
    restart: unless-stopped
    command: "node app.js"
    environment:
     - MONGODB_PROD_URI=${MONGODB_URI}
     - MONGODB_LOCAL_URI=mongodb://mongo:27017/test
     - JWTSECRET=${JWTSECRET}
     - SESSION_SECRET=${SESSION_SECRET}
     - SENDGRID_API_KEY=${SENDGRID_API_KEY}
     - SENDGRID_EMAIL_ADDRESS=${SENDGRID_EMAIL_ADDRESS}
     - COMPANY_NAME=${COMPANY_NAME}
     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
     - S3_BUCKET=${S3_BUCKET}
     - AWS_REGION=${AWS_REGION}
     - HOST=${HOST}
     - PORT=${PORT}
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    container_name: mongo
  nginx:
    image: "nginx"
    container_name: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static_files:/var/www
    ports: 
     - 80:80
     - 443:443
    depends_on:
      - app
